"""Add voice field to USER model

Revision ID: 591dd84a3442
Revises: 113d63e74b5a
Create Date: 2024-02-15 17:42:36.717623

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "591dd84a3442"
down_revision: Union[str, None] = "113d63e74b5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users_table", sa.Column("voice", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users_table", "voice")
    # ### end Alembic commands ###
